# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: Homeless Outreach Street Team Documentation
subtitle: 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/HOST'

# Author/Organization info to be displayed in the templates
author:
  name: City of Austin
  url: http://austintexas.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Foundation
  url:  /foundation
  internal: true
- text: Framing the HOST Pilot
  url:  pilot_frame
  internal: true
- text: Strategy
  url: strategy
  internal: true
- text: How Host Fits In
  url: how_host_fits_in
  internal: true 
- text: Designing HOST
  url: designing_host
  internal: true
# - text: Another Page
#   url: these are linked in the _config.yml file
#   internal: false

# Repo list
# List repos that you would like to appear on the homepage here
# repos:
# - name: DOCter
#   description: Jekyll template for docs
#   url: https://github.com/cfpb/DOCter

# Style Variables
brand_color: "#33578E"

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
